# Generated by Django 2.2 on 2020-04-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=32, unique=True)),
                ('u_password', models.CharField(max_length=256)),
                ('u_email', models.CharField(max_length=64, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('u_level', models.IntegerField(default=0)),
                ('u_vip_expire_time', models.IntegerField(default=1586909742)),
            ],
            options={
                'db_table': 'wa_user',
            },
        ),
        migrations.CreateModel(
            name='Vip_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_month', models.IntegerField(default=0)),
                ('v_start_time', models.IntegerField(default=1586909742)),
                ('last_change_time', models.DateTimeField(auto_now=True)),
                ('v_status', models.IntegerField(default=2)),
                ('v_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
            options={
                'db_table': 'wa_vip_order',
            },
        ),
    ]
