# Generated by Django 2.2 on 2020-04-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200415_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_order',
            name='v_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_vip_expire_time',
            field=models.IntegerField(default=1586910897),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_start_time',
            field=models.IntegerField(default=1586910897),
        ),
    ]
