# Generated by Django 2.2 on 2020-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200415_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_order',
            name='v_expire_time',
            field=models.IntegerField(default=1586912373),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_vip_expire_time',
            field=models.IntegerField(default=1586912373),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_start_time',
            field=models.IntegerField(default=1586912373),
        ),
    ]
