# Generated by Django 2.2 on 2020-04-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200415_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_fakeid', models.CharField(max_length=32, unique=True)),
                ('a_name', models.CharField(max_length=50)),
                ('a_wxid', models.CharField(max_length=32)),
                ('a_head_img', models.CharField(max_length=255)),
                ('a_intro', models.CharField(max_length=255)),
                ('a_type', models.CharField(max_length=10)),
                ('a_update_time', models.IntegerField(default=1586918490)),
            ],
            options={
                'db_table': 'wa_account',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='u_vip_expire_time',
            field=models.IntegerField(default=1586918490),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_expire_time',
            field=models.IntegerField(default=1586918490),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_start_time',
            field=models.IntegerField(default=1586918490),
        ),
    ]
