# Generated by Django 2.2 on 2020-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200415_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'wa_type',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='a_update_time',
            field=models.IntegerField(default=1586932286),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_vip_expire_time',
            field=models.IntegerField(default=1586932286),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_expire_time',
            field=models.IntegerField(default=1586932286),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_start_time',
            field=models.IntegerField(default=1586932286),
        ),
    ]
