# Generated by Django 2.2 on 2020-04-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200415_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='a_update_time',
            field=models.IntegerField(default=1586997972),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_vip_expire_time',
            field=models.IntegerField(default=1586997972),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_expire_time',
            field=models.IntegerField(default=1586997972),
        ),
        migrations.AlterField(
            model_name='vip_order',
            name='v_start_time',
            field=models.IntegerField(default=1586997972),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_title', models.CharField(max_length=64)),
                ('w_cover', models.CharField(max_length=255)),
                ('w_link', models.CharField(max_length=255, unique=True)),
                ('w_idx', models.IntegerField(default=0)),
                ('w_create_time', models.IntegerField(default=1586997972)),
                ('w_update_time', models.IntegerField(default=1586997972)),
                ('w_read_num', models.IntegerField(default=0)),
                ('w_watch_num', models.IntegerField(default=0)),
                ('w_admire_num', models.IntegerField(default=0)),
                ('w_crawl_time', models.IntegerField(default=1586997972)),
                ('w_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Account')),
            ],
            options={
                'db_table': 'wa_article',
            },
        ),
    ]
