# Generated by Django 2.2 on 2020-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200416_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='w_status',
            field=models.IntegerField(default=0),
        ),
    ]
