# Generated by Django 2.2 on 2020-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_article_w_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='r_not_origin_avg',
        ),
    ]
