# Generated by Django 2.2 on 2020-04-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_rank_r_not_origin_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_status', models.IntegerField(default=0)),
                ('f_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Account')),
                ('f_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
            options={
                'db_table': 'wa_follow',
            },
        ),
    ]
