# Generated by Django 2.2 on 2020-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='a_change_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
